apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: emissary-ingress-listener-8080
  namespace: emissary
spec:
  hostBinding:
    namespace:
      from: ALL
  port: 8080
  protocol: HTTP
  securityModel: XFP
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: default-host
spec:
  hostname: '*'
  mappingSelector:
    matchLabels:
      defaulthost: host
  requestPolicy:
    insecure:
      action: Route
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  labels:
    defaulthost: host
  name: root-mapping
spec:
  prefix: /
  prefix_redirect: /lobbies
  service: lobbies-spa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: words
spec:
  selector:
    matchLabels:
      app: words
  template:
    metadata:
      labels:
        app: words
    spec:
      containers:
        - image: ghcr.io/deesejohn/words:0e5d336@sha256:b5512082d3ebc69c77ef37357280df6d482b605aa297e1b6ef07670257fc296d
          livenessProbe:
            grpc:
              port: 50051
          name: server
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: words
spec:
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  selector:
    app: words
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: games
spec:
  selector:
    matchLabels:
      app: games
  template:
    metadata:
      labels:
        app: games
    spec:
      containers:
        - env:
            - name: NATS_HOST
              value: my-nats
            - name: REDIS_HOST
              value: games-redis-master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: games-redis
            - name: WORDS_ADDRESS
              value: words:50051
          image: ghcr.io/deesejohn/games:0e5d336@sha256:dc17834d7575ec783b7db3e6b5bfd419e3357afa9b4aeba8994a50d24cd9c5cf
          livenessProbe:
            grpc:
              port: 50051
          name: server
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: games
spec:
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  selector:
    app: games
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-bff
spec:
  selector:
    matchLabels:
      app: games-bff
  template:
    metadata:
      labels:
        app: games-bff
    spec:
      containers:
        - env:
            - name: GAMES_HOST
              value: games:50051
            - name: HOST_PREFIX
              value: /api/games
            - name: NATS_HOST
              value: my-nats
          image: ghcr.io/deesejohn/games-bff:0e5d336@sha256:84a63481764b6323f171da4c5425946c04970b5ec3791cb04f397d67d0640155
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8000
            initialDelaySeconds: 5
          name: server
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8000
            initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: games-bff
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: games-bff
  type: ClusterIP
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  labels:
    defaulthost: host
  name: games-bff-mapping
spec:
  allow_upgrade:
    - websocket
  prefix: /api/games/
  service: games-bff
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-spa
spec:
  selector:
    matchLabels:
      app: games-spa
  template:
    metadata:
      labels:
        app: games-spa
    spec:
      containers:
        - image: ghcr.io/deesejohn/games-spa:0e5d336@sha256:6feb36a06da7776f818d051de6e7773223d806e3a2f09a4c2cbf2ef2511796b0
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
          name: server
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: games-spa
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: games-spa
  type: ClusterIP
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  labels:
    defaulthost: host
  name: games-spa-mapping
spec:
  prefix: /games
  service: games-spa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobbies
spec:
  selector:
    matchLabels:
      app: lobbies
  template:
    metadata:
      labels:
        app: lobbies
    spec:
      containers:
        - env:
            - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
              value: "true"
            - name: GAMES_HOST
              value: http://games:50051
            - name: HOST_PREFIX
              value: /api/lobbies
            - name: PLAYERS_HOST
              value: http://players
            - name: REDIS_HOST
              value: lobbies-redis-master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: lobbies-redis
          image: ghcr.io/deesejohn/lobbies:0e5d336@sha256:3b27f0b9b0cce4a2e545960179b4884c747b7437e89e697da21829f7e4503c0d
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
          name: server
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lobbies
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: lobbies
  type: ClusterIP
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  labels:
    defaulthost: host
  name: lobbies-mapping
spec:
  allow_upgrade:
    - websocket
  prefix: /api/lobbies/
  service: lobbies
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobbies-spa
spec:
  selector:
    matchLabels:
      app: lobbies-spa
  template:
    metadata:
      labels:
        app: lobbies-spa
    spec:
      containers:
        - image: ghcr.io/deesejohn/lobbies-spa:0e5d336@sha256:24699efa77bc14e7c370cd8dbe49f65c2bd0e58bbd26eac1b54ceda0a7936731
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
          name: server
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lobbies-spa
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: lobbies-spa
  type: ClusterIP
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  labels:
    defaulthost: host
  name: lobbies-spa-mapping
spec:
  prefix: /lobbies
  service: lobbies-spa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: players
spec:
  selector:
    matchLabels:
      app: players
  template:
    metadata:
      labels:
        app: players
    spec:
      containers:
        - env:
            - name: HOST_PREFIX
              value: /api/players
            - name: REDIS_HOST
              value: players-redis-master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: players-redis
          image: ghcr.io/deesejohn/players:0e5d336@sha256:282b558177dcd1e915a2b00dc7fb8b874d599d3fc954cb74539d59e3131a2880
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
          name: server
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: players
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: players
  type: ClusterIP
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  labels:
    defaulthost: host
  name: players-mapping
spec:
  prefix: /api/players/
  service: players
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: players-spa
spec:
  selector:
    matchLabels:
      app: players-spa
  template:
    metadata:
      labels:
        app: players-spa
    spec:
      containers:
        - image: ghcr.io/deesejohn/players-spa:0e5d336@sha256:8e36904907218248fe3ad5a08d243675bd71fc259c8307e1b8bf62d3ac755aff
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
          name: server
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: players-spa
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: players-spa
  type: ClusterIP
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  labels:
    defaulthost: host
  name: players-spa-mapping
spec:
  prefix: /players
  service: players-spa
