apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: emissary-ingress-listener-8080
  namespace: emissary
spec:
  hostBinding:
    namespace:
      from: ALL
  port: 8080
  protocol: HTTP
  securityModel: XFP
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: default-host
spec:
  hostname: '*'
  mappingSelector:
    matchLabels:
      defaulthost: host
  requestPolicy:
    insecure:
      action: Route
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  labels:
    defaulthost: host
  name: root-mapping
spec:
  prefix: /
  prefix_redirect: /lobbies
  service: lobbies-spa

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: words
spec:
  selector:
    matchLabels:
      app: words
  template:
    metadata:
      labels:
        app: words
    spec:
      containers:
      - image: ghcr.io/deesejohn/words:ee8639c@sha256:20dba1388d8225f6185393b225d89efeb97d4f6227b0f95fc6f0dd169d5ded79
        livenessProbe:
          grpc:
            port: 50051
        name: server
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: words
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: words
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: games
spec:
  selector:
    matchLabels:
      app: games
  template:
    metadata:
      labels:
        app: games
    spec:
      containers:
      - env:
        - name: NATS_HOST
          value: my-nats
        - name: REDIS_HOST
          value: games-redis-master
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: games-redis
        - name: WORDS_ADDRESS
          value: words:50051
        image: ghcr.io/deesejohn/games:ee8639c@sha256:431cc04b738d1c05e610a13d21bf83a8fc35b32c664ed50c25fd0ed290a04092
        livenessProbe:
          grpc:
            port: 50051
        name: server
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: games
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: games
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-bff
spec:
  selector:
    matchLabels:
      app: games-bff
  template:
    metadata:
      labels:
        app: games-bff
    spec:
      containers:
      - env:
        - name: GAMES_HOST
          value: games:50051
        - name: HOST_PREFIX
          value: /api/games
        - name: NATS_HOST
          value: my-nats
        image: ghcr.io/deesejohn/games-bff:ee8639c@sha256:9d637493ee0103f8d88fd9295fdb762a556bed0cb8898cbb9f8028d808cbb4e6
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
          initialDelaySeconds: 5
        name: server
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: games-bff
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
  selector:
    app: games-bff
  type: ClusterIP
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  labels:
    defaulthost: host
  name: games-bff-mapping
spec:
  allow_upgrade:
  - websocket
  prefix: /api/games/
  service: games-bff

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-spa
spec:
  selector:
    matchLabels:
      app: games-spa
  template:
    metadata:
      labels:
        app: games-spa
    spec:
      containers:
      - image: ghcr.io/deesejohn/games-spa:ee8639c@sha256:038b23cb201aa54ed6558e2731b85c42b7a847ad8b6d6ba28e7da0e3e24fef68
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
        name: server
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: games-spa
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: games-spa
  type: ClusterIP
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  labels:
    defaulthost: host
  name: games-spa-mapping
spec:
  prefix: /games
  service: games-spa

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobbies
spec:
  selector:
    matchLabels:
      app: lobbies
  template:
    metadata:
      labels:
        app: lobbies
    spec:
      containers:
      - env:
        - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
          value: "true"
        - name: GAMES_HOST
          value: http://games:50051
        - name: HOST_PREFIX
          value: /api/lobbies
        - name: PLAYERS_HOST
          value: http://players
        - name: REDIS_HOST
          value: lobbies-redis-master
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: lobbies-redis
        image: ghcr.io/deesejohn/lobbies:ee8639c@sha256:54c8ef459ee4236f7d6624eedb19a757eff91092f98ed4cf8c7364fb3ddec32c
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
        name: server
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lobbies
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: lobbies
  type: ClusterIP
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  labels:
    defaulthost: host
  name: lobbies-mapping
spec:
  allow_upgrade:
  - websocket
  prefix: /api/lobbies/
  service: lobbies

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobbies-spa
spec:
  selector:
    matchLabels:
      app: lobbies-spa
  template:
    metadata:
      labels:
        app: lobbies-spa
    spec:
      containers:
      - image: ghcr.io/deesejohn/lobbies-spa:ee8639c@sha256:dd0e71f0e943f8d4a3ee342150f4e553a0ec5923230beac48842f02ecdd00aec
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
        name: server
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lobbies-spa
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: lobbies-spa
  type: ClusterIP
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  labels:
    defaulthost: host
  name: lobbies-spa-mapping
spec:
  prefix: /lobbies
  service: lobbies-spa

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: players
spec:
  selector:
    matchLabels:
      app: players
  template:
    metadata:
      labels:
        app: players
    spec:
      containers:
      - env:
        - name: HOST_PREFIX
          value: /api/players
        - name: REDIS_HOST
          value: players-redis-master
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: players-redis
        image: ghcr.io/deesejohn/players:ee8639c@sha256:7ef42047041a6f23678cbb84457e023d134b275554fac2dabef3b0d12d45ef45
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
        name: server
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: players
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: players
  type: ClusterIP
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  labels:
    defaulthost: host
  name: players-mapping
spec:
  prefix: /api/players/
  service: players

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: players-spa
spec:
  selector:
    matchLabels:
      app: players-spa
  template:
    metadata:
      labels:
        app: players-spa
    spec:
      containers:
      - image: ghcr.io/deesejohn/players-spa:ee8639c@sha256:3003096a235f199a33ed605b5f08d02df96b83ee6426d976b800fd29515b361f
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
        name: server
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: players-spa
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: players-spa
  type: ClusterIP
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  labels:
    defaulthost: host
  name: players-spa-mapping
spec:
  prefix: /players
  service: players-spa
