apiVersion: apps/v1
kind: Deployment
metadata:
  name: games
spec:
  selector:
    matchLabels:
      app: games
  template:
    metadata:
      labels:
        app: games
    spec:
      containers:
      - env:
        - name: NATS_HOST
          value: my-nats
        - name: REDIS_HOST
          value: games-redis-master
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: games-redis
        - name: WORDS_ADDRESS
          value: words:50051
        image: ghcr.io/deesejohn/games:9eda0d5@sha256:b6bdd666d9530ef00fb61e2660332703e25f3b45dbd6f519e43b75baba343715
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50051
          initialDelaySeconds: 10
        name: server
        ports:
        - containerPort: 50051
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50051
          initialDelaySeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: games
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: games
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-bff
spec:
  selector:
    matchLabels:
      app: games-bff
  template:
    metadata:
      labels:
        app: games-bff
    spec:
      containers:
      - env:
        - name: GAMES_HOST
          value: games:50051
        - name: HOST_PREFIX
          value: /api/games
        - name: NATS_HOST
          value: my-nats
        image: ghcr.io/deesejohn/games-bff:9eda0d5@sha256:b422adf7539e1b96795fd244d6dde5821268adcb77a013a88806ccd0a129d464
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
          initialDelaySeconds: 5
        name: server
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: games-bff
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
  selector:
    app: games-bff
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: games-bff-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: games-bff
            port:
              number: 80
        path: /api/games(/|$)(.*)
        pathType: Prefix

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-spa
spec:
  selector:
    matchLabels:
      app: games-spa
  template:
    metadata:
      labels:
        app: games-spa
    spec:
      containers:
      - image: ghcr.io/deesejohn/games-spa:9eda0d5@sha256:6754044ce79e7264c5bf67627c374e8fa0bcd339b1081b5b3a8a9131bfaa6b3b
        name: server
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: games-spa
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: games-spa
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: games-spa-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: games-spa
            port:
              number: 80
        path: /games(/|$)(.*)
        pathType: Prefix

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobbies
spec:
  selector:
    matchLabels:
      app: lobbies
  template:
    metadata:
      labels:
        app: lobbies
    spec:
      containers:
      - env:
        - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
          value: "true"
        - name: GAMES_HOST
          value: http://games:50051
        - name: HOST_PREFIX
          value: /api/lobbies
        - name: PLAYERS_HOST
          value: http://players
        - name: REDIS_HOST
          value: lobbies-redis-master
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: lobbies-redis
        image: ghcr.io/deesejohn/lobbies:9eda0d5@sha256:1b4d66a3da6ea89ffd603f28244d4e63b6ecd7b3a1235923463c48df158c6703
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
          initialDelaySeconds: 5
        name: server
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: lobbies
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: lobbies
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: lobbies-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: lobbies
            port:
              number: 80
        path: /api/lobbies(/|$)(.*)
        pathType: Prefix

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobbies-spa
spec:
  selector:
    matchLabels:
      app: lobbies-spa
  template:
    metadata:
      labels:
        app: lobbies-spa
    spec:
      containers:
      - image: ghcr.io/deesejohn/lobbies-spa:9eda0d5@sha256:177f034da7d3274732f18050209795a25c554fa58c6eb0037da3367757b7b383
        name: server
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: lobbies-spa
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: lobbies-spa
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: lobbies-spa-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: lobbies-spa
            port:
              number: 80
        path: /lobbies(/|$)(.*)
        pathType: Prefix

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: players
spec:
  selector:
    matchLabels:
      app: players
  template:
    metadata:
      labels:
        app: players
    spec:
      containers:
      - env:
        - name: HOST_PREFIX
          value: /api/players
        - name: REDIS_HOST
          value: players-redis-master
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: players-redis
        image: ghcr.io/deesejohn/players:9eda0d5@sha256:0d4d97c1cab9466d9530e127084ea96cc605748daea7ccbc2dd387dc0235c161
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
          initialDelaySeconds: 5
        name: server
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: players
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: players
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: players-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: players
            port:
              number: 80
        path: /api/players(/|$)(.*)
        pathType: Prefix

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: players-spa
spec:
  selector:
    matchLabels:
      app: players-spa
  template:
    metadata:
      labels:
        app: players-spa
    spec:
      containers:
      - image: ghcr.io/deesejohn/players-spa:9eda0d5@sha256:7e44e814af4dfc7db1ba66707e303cace3a956799e0042dcabee67ab069603fe
        name: server
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: players-spa
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: players-spa
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: players-spa-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: players-spa
            port:
              number: 80
        path: /players(/|$)(.*)
        pathType: Prefix

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: words
spec:
  selector:
    matchLabels:
      app: words
  template:
    metadata:
      labels:
        app: words
    spec:
      containers:
      - image: ghcr.io/deesejohn/words:9eda0d5@sha256:084d7d5e2455f3ed569fa00ca6413494d5529543ef5e724bdc0bb156f02247d4
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50051
          initialDelaySeconds: 10
        name: server
        ports:
        - containerPort: 50051
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50051
          initialDelaySeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: words
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: words
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      return 301 /lobbies;
  name: default-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: default-backend
            port:
              number: 80
        path: /
        pathType: Prefix
